### PR TITLE
Put dummy text inside comments, looks neater

### PR DESCRIPTION
**Pull request by juzerali**

### CODE REVIEW

**Comment by seanjames777** [comment]
I feel like this would be inconsistent with the rest of the snippets. We need to decide on a rule for this, since anonymous functions (fn) and case statements, if statements, etc. all have a code body. If we're going to insert comments in one of them we should do it in all of them.

Additionally, since a function body is required in SML unlike C or something, the user's going to have to replace the prompt with something regardless of what the prompt says.

**Comment by juzerali** [comment]
Could you please enable github issues for this project? I wanted to point out a couple of things. Like textmate packages works out of the box with sublime, there isn't a need for JSON-\* files. Secondly, did you by any chance rebased the master and force pushed on the repo? I am unable to pull the changes.

Regarding comments issue, lets keep it open for now.

**Comment by seanjames777** [comment]
> Could you please enable github issues for this project?

Yes.

> Secondly, did you by any chance rebased the master and force pushed on the repo? I am unable to pull the 
> changes.

Nope.

**Comment by seanjames777** [comment]
Closed because we haven't touched it for months.

**Pull request closed without merging**
